CREATE SEQUENCE seqTipoLancamento START WITH 1
CREATE SEQUENCE seqLancamento START WITH 1

CREATE TABLE TipoLancamento
(idTipoLancamento INTEGER GENERATED BY DEFAULT AS SEQUENCE seqTipoLancamento PRIMARY KEY,
descricaoTipoLancamento varchar(100))

INSERT INTO TipoLancamento
VALUES (1, 'Alimentação')
INSERT INTO TipoLancamento
VALUES (2, 'Moradia')
INSERT INTO TipoLancamento
VALUES (3, 'Educação')
INSERT INTO TipoLancamento
VALUES (4, 'Transporte')
INSERT INTO TipoLancamento
VALUES (5, 'Saúde')
INSERT INTO TipoLancamento
VALUES (6, 'Lazer')
INSERT INTO TipoLancamento
VALUES (7, 'Outros')

CREATE TABLE LancamentoMensal 
(idLancamento INTEGER GENERATED BY DEFAULT AS SEQUENCE seqLancamento PRIMARY KEY, 
   descricaoLancamento VARCHAR(255),
   dataLancamento date,
   valorLancamento decimal(10,2),
   idTipoLancamento int FOREIGN KEY REFERENCES TipoLancamento(idTipoLancamento))
